import { randomUUID } from 'node:crypto';
import { createWriteStream } from 'node:fs';
import { rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { once } from 'node:events';
import {
  AppError,
  ConflictError,
  NotFoundError,
  PermissionDeniedError,
  ValidationError,
} from '../../domain/errors.js';
import type { Transaction } from '../../database/client.js';
import { AccountingPermissions } from '../../modules/accounting/index.js';
import { recordAuditEvent } from '../../modules/audit/index.js';
import {
  CSV_BOM,
  csvRecord,
  getExport,
  insertExport,
  listExports,
  updateExport,
  type DataExport,
  type ExportDomainKey,
} from '../../modules/data-exchange/index.js';
import {
  hasPermission,
  requirePermission,
  resolveActingUserContext,
  type AuthorizationContext,
  type Principal,
} from '../authorization.js';
import type { AppDependencies } from '../dependencies.js';
import type { FileService } from '../file-service.js';
import type { JobContext, JobService } from '../job-service.js';
import { withOrganization } from '../organization-service.js';
import { inTransaction } from '../unit-of-work.js';
import { exportDomains } from './exports.js';
import type { DomainServices, ExportCell, ExportDomain } from './types.js';

/**
 * Exports (S6-26..S6-33; L-5, L-12). An export is generated by a job under the requesting
 * user's current permissions, written as CSV (formula-neutralized) to a temporary file with a
 * 25 MB cap, stored as an S5 file linked to the export and expired after 7 days. Every access
 * re-checks the export's permissions for the current user (correction 3).
 */

export const EXPORT_GENERATE_JOB = 'export.generate';

class ExportTooLargeError extends AppError {
  constructor(limit: number) {
    super(
      'EXPORT_TOO_LARGE',
      413,
      `The export is larger than ${Math.round(limit / (1024 * 1024))} MB. Narrow the date range or filters and try again.`,
    );
  }
}

/** Params that carry dimension data need accounting.dimensions.view as well (Decisions 91, 92). */
function dimensionPermissionNeeded(params: Record<string, unknown>): boolean {
  const ids = params.dimensionValueIds;
  return (typeof ids === 'string' && ids.trim() !== '') || params.includeDimensions === true;
}

export function exportDomain(key: ExportDomainKey): ExportDomain<never> {
  const domain = exportDomains.get(key);
  if (!domain) throw new ValidationError([{ path: 'domain', message: 'Unknown export type.' }]);
  return domain;
}

export function parseExportParams(
  domain: ExportDomain<never>,
  params: Record<string, unknown>,
): never {
  const result = domain.params.safeParse(params);
  if (!result.success) {
    throw new ValidationError(
      result.error.issues.map((i) => ({
        path: ['params', ...i.path.map(String)].join('.'),
        message: i.message,
      })),
    );
  }
  return result.data;
}

/**
 * The current user may access this export (correction 3): its recorded permission, the
 * dimension permission when it carries dimension data, and the domain's own rule, all
 * evaluated against the user's current permissions. Tenant isolation comes from RLS and the
 * organization-scoped lookup that loaded `e`.
 */
export async function assertExportAccess(
  tx: Transaction,
  ctx: AuthorizationContext,
  e: DataExport,
): Promise<ExportDomain<never>> {
  if (e.organizationId !== ctx.organizationId) throw new NotFoundError('Export not found.');
  const domain = exportDomain(e.domain);
  requirePermission(ctx, e.requiredPermission);
  if (
    dimensionPermissionNeeded(e.params) &&
    !hasPermission(ctx, AccountingPermissions.DimensionsView)
  ) {
    throw new PermissionDeniedError('You need permission to view dimensions to open this export.');
  }
  await domain.permission(parseExportParams(domain, e.params), { tx, ctx });
  return domain;
}

export function exportView(e: DataExport, domain: ExportDomain<never>) {
  return {
    id: e.id,
    domain: e.domain,
    domainLabel: domain.label,
    format: e.format,
    status: e.status,
    params: e.params,
    rowCount: e.rowCount,
    fileId: e.status === 'ready' ? e.fileId : null,
    error: e.error,
    createdByUserId: e.createdByUserId,
    createdAt: e.createdAt.toISOString(),
    finishedAt: e.finishedAt?.toISOString() ?? null,
    expiresAt: e.expiresAt.toISOString(),
  };
}

export class ExportService {
  constructor(
    private readonly deps: AppDependencies,
    private readonly services: DomainServices,
    private readonly files: FileService,
    private readonly jobs: JobService,
  ) {}

  private get now() {
    return this.deps.clock.now();
  }

  domain(key: ExportDomainKey): ExportDomain<never> {
    return exportDomain(key);
  }

  private parse(domain: ExportDomain<never>, params: Record<string, unknown>): never {
    return parseExportParams(domain, params);
  }

  assertAccess(tx: Transaction, ctx: AuthorizationContext, e: DataExport) {
    return assertExportAccess(tx, ctx, e);
  }

  create(
    principal: Principal,
    input: { domain: ExportDomainKey; params: Record<string, unknown> },
  ) {
    const domain = this.domain(input.domain);
    return withOrganization(this.deps, principal, {}, async (tx, ctx) => {
      const params = this.parse(domain, input.params);
      const permission = await domain.permission(params, { tx, ctx });
      requirePermission(ctx, permission);
      if (
        dimensionPermissionNeeded(input.params) &&
        !hasPermission(ctx, AccountingPermissions.DimensionsView)
      ) {
        throw new PermissionDeniedError(
          'You need permission to view dimensions to export dimension data.',
        );
      }
      const created = await insertExport(tx, {
        organizationId: ctx.organizationId,
        domain: domain.key,
        // Raw parameters: re-parsed (with the same schema) when the job runs.
        params: input.params,
        requiredPermission: permission,
        userId: ctx.userId,
        expiresAt: new Date(this.now.getTime() + this.deps.config.dataExchange.exportExpiryMs),
      });
      const { job } = await this.jobs.enqueue(tx, {
        organizationId: ctx.organizationId,
        type: EXPORT_GENERATE_JOB,
        jobKey: `${EXPORT_GENERATE_JOB}:${created.id}`,
        payload: { exportId: created.id, userId: ctx.userId },
        requiredPermission: permission,
        createdByUserId: ctx.userId,
      });
      return { export: exportView(created, domain), jobId: job.id };
    });
  }

  get(principal: Principal, exportId: string) {
    return withOrganization(this.deps, principal, {}, async (tx, ctx) => {
      const e = await getExport(tx, ctx.organizationId, exportId);
      if (!e) throw new NotFoundError('Export not found.');
      return exportView(e, await this.assertAccess(tx, ctx, e));
    });
  }

  /** The user's own exports that they may still open. */
  list(principal: Principal, query: { limit: number; before?: string | undefined }) {
    return withOrganization(this.deps, principal, {}, async (tx, ctx) => {
      const exportsList = await listExports(tx, ctx.organizationId, {
        limit: query.limit,
        before: query.before ? new Date(query.before) : undefined,
      });
      const result = [];
      for (const e of exportsList) {
        if (e.createdByUserId !== ctx.userId) continue;
        try {
          result.push(exportView(e, await this.assertAccess(tx, ctx, e)));
        } catch (error) {
          if (!(error instanceof AppError)) throw error;
        }
      }
      return result;
    });
  }

  /** A signed download link for a ready export (S5-08), after the access re-check. */
  async downloadUrl(principal: Principal, exportId: string) {
    const fileId = await withOrganization(this.deps, principal, {}, async (tx, ctx) => {
      const e = await getExport(tx, ctx.organizationId, exportId);
      if (!e) throw new NotFoundError('Export not found.');
      await this.assertAccess(tx, ctx, e);
      if (e.status !== 'ready' || !e.fileId) {
        throw new ConflictError('INVALID_STATE_TRANSITION', 'This export has no file to download.');
      }
      return e.fileId;
    });
    return this.files.downloadUrl(principal, fileId);
  }

  // ---------------------------------------------------------------------------
  // export.generate (S6-26)
  // ---------------------------------------------------------------------------

  async runGenerate(job: JobContext) {
    const payload = job.job.payload as { exportId: string; userId: string };
    const started = await job.run(async (tx) => {
      const e = await getExport(tx, job.organizationId, payload.exportId, { forUpdate: true });
      if (!e || (e.status !== 'queued' && e.status !== 'running')) return null;
      return (await updateExport(tx, job.organizationId, e.id, { status: 'running' }))!;
    });
    if (!started) return { skipped: true };
    const temporary = path.join(tmpdir(), `intuit2-export-${randomUUID()}.csv`);
    try {
      const domain = this.domain(started.domain);
      // 1. Generate in one consistent, read-only snapshot (statements: REPEATABLE READ).
      const rowCount = await inTransaction(
        this.deps.db,
        { organizationId: job.organizationId },
        async (tx) => {
          const ctx = await resolveActingUserContext(tx, payload.userId, job.organizationId);
          await this.assertAccess(tx, ctx, started);
          return this.writeFile(temporary, (write) =>
            domain.generate(
              { tx, ctx, services: this.services, now: this.now, write },
              this.parse(domain, started.params),
            ),
          );
        },
        { readOnlySnapshot: true },
      );
      // 2. Store it and mark the export ready (L-12: generation is audited, downloads are not).
      return await job.run(async (tx) => {
        const ctx = await resolveActingUserContext(tx, payload.userId, job.organizationId);
        const file = await this.files.storeGeneratedInTransaction(tx, ctx, {
          linkType: 'export',
          linkId: started.id,
          fileName: domain.fileName(this.parse(domain, started.params), this.now),
          sourcePath: temporary,
        });
        await updateExport(tx, job.organizationId, started.id, {
          status: 'ready',
          fileId: file.id,
          rowCount,
          finishedAt: this.now,
        });
        await recordAuditEvent(tx, {
          occurredAt: this.now,
          organizationId: job.organizationId,
          actorUserId: ctx.userId,
          action: 'export.generated',
          resourceType: 'export',
          resourceId: started.id,
          metadata: {
            domain: started.domain,
            format: started.format,
            params: started.params,
            rows: rowCount,
            fileId: file.id,
            size: file.sizeBytes,
          },
          origin: { requestId: `export:${started.id}`, ipAddress: null, userAgent: null },
        });
        return { status: 'ready', rows: rowCount };
      });
    } catch (error) {
      if (!(error instanceof AppError)) throw error; // transient: retried by the job runner
      await job.run(async (tx) => {
        await updateExport(tx, job.organizationId, started.id, {
          status: 'failed',
          error: error.message.slice(0, 500),
          finishedAt: this.now,
        });
      });
      return { status: 'failed' };
    } finally {
      await rm(temporary, { force: true });
    }
  }

  /** Streams records to a temporary file, enforcing the export size cap (S6-28, L-5). */
  private async writeFile(
    target: string,
    produce: (write: (cells: readonly ExportCell[]) => Promise<void>) => Promise<number>,
  ): Promise<number> {
    const limit = this.deps.config.dataExchange.exportMaxBytes;
    const out = createWriteStream(target, { flags: 'wx' });
    // Failures surface through once(); after destroy() late write errors are expected.
    out.on('error', () => undefined);
    let bytes = 0;
    const push = async (text: string) => {
      bytes += Buffer.byteLength(text);
      if (bytes > limit) throw new ExportTooLargeError(limit);
      if (!out.write(text)) await once(out, 'drain');
    };
    try {
      await push(CSV_BOM);
      const rows = await produce((cells) => push(csvRecord(cells)));
      out.end();
      await once(out, 'finish');
      return rows;
    } catch (error) {
      out.destroy();
      await once(out, 'close').catch(() => undefined);
      throw error;
    }
  }
}
