import { sql } from 'drizzle-orm';
import {
  bigint,
  boolean,
  char,
  date,
  integer,
  jsonb,
  numeric,
  pgTable,
  primaryKey,
  text,
  uuid,
} from 'drizzle-orm/pg-core';
import { timestamptz } from '../../database/column-types.js';

/** Phase 4A-4: Purchases settings and document numbering (migration 0030; ADR 0004). */

/**
 * Purchases document number sequences (P4-51). `debit_note` has its own sequence because debit
 * notes get their own `DN-` numbers (P4-23, P4-51).
 */
export const purchaseDocumentTypes = [
  'bill',
  'vendor_credit',
  'debit_note',
  'vendor_payment',
  'vendor_refund',
  'expense',
] as const;
export type PurchaseDocumentType = (typeof purchaseDocumentTypes)[number];

export const purchasesSettings = pgTable('purchases_settings', {
  organizationId: uuid('organization_id').primaryKey(),
  /** The AP control account, owned by the `purchases` subledger (P4-07, P4-08). */
  apAccountId: uuid('ap_account_id'),
  defaultExpenseAccountId: uuid('default_expense_account_id'),
  /** Default bank, cash or card account for vendor payments (P4-26). */
  defaultPaymentAccountId: uuid('default_payment_account_id'),
  defaultTaxCodeId: uuid('default_tax_code_id'),
  defaultTaxTreatment: text('default_tax_treatment', {
    enum: ['exclusive', 'inclusive', 'no_tax'],
  })
    .notNull()
    .default('exclusive'),
  defaultPaymentTermsDays: integer('default_payment_terms_days').notNull().default(30),
  /** Set by the first Purchases posting: the AP control account is fixed from then on. */
  apLockedAt: timestamptz('ap_locked_at'),
  version: integer('version').notNull().default(1),
  createdByUserId: uuid('created_by_user_id').notNull(),
  createdAt: timestamptz('created_at').notNull(),
  updatedByUserId: uuid('updated_by_user_id'),
  updatedAt: timestamptz('updated_at').notNull(),
});

export const purchasesNumberSequences = pgTable(
  'purchases_number_sequences',
  {
    organizationId: uuid('organization_id').notNull(),
    documentType: text('document_type', { enum: purchaseDocumentTypes }).notNull(),
    prefix: text('prefix').notNull().default(''),
    minDigits: integer('min_digits').notNull().default(5),
    nextNumber: bigint('next_number', { mode: 'number' }).notNull().default(1),
    version: integer('version').notNull().default(1),
    updatedByUserId: uuid('updated_by_user_id'),
    updatedAt: timestamptz('updated_at').notNull(),
  },
  (t) => [primaryKey({ columns: [t.organizationId, t.documentType] })],
);

// ---------------------------------------------------------------------------
// Bills (migration 0033; ADR 0004 P4-15 to P4-22)
// ---------------------------------------------------------------------------

export const billStatuses = ['DRAFT', 'PENDING_APPROVAL', 'POSTED', 'VOID'] as const;
export type BillStatus = (typeof billStatuses)[number];
export const billKinds = ['standard'] as const;
export type BillKind = (typeof billKinds)[number];

const money = (name: string) => numeric(name, { precision: 28, scale: 4 });

export const purchasesBills = pgTable('purchases_bills', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull(),
  kind: text('kind', { enum: billKinds }).notNull().default('standard'),
  status: text('status', { enum: billStatuses }).notNull().default('DRAFT'),
  vendorId: uuid('vendor_id').notNull(),
  number: text('number'),
  /** The supplier's invoice number, kept as entered (P4-17). */
  vendorReference: text('vendor_reference'),
  /** Generated: the reference ignoring case and whitespace (P4-18 duplicate key). */
  vendorReferenceKey: text('vendor_reference_key').generatedAlwaysAs(
    // Documentation only: the column is generated by the database (migration 0033).
    sql`upper(regexp_replace(vendor_reference, '\\s', '', 'g'))`,
  ),
  billDate: date('bill_date', { mode: 'string' }).notNull(),
  dueDate: date('due_date', { mode: 'string' }).notNull(),
  paymentTermsDays: integer('payment_terms_days'),
  currencyCode: char('currency_code', { length: 3 }).notNull(),
  /** A requested manual rate and its mandatory reason (P4-16). */
  rateOverride: numeric('rate_override', { precision: 28, scale: 10 }),
  rateOverrideReason: text('rate_override_reason'),
  exchangeRate: numeric('exchange_rate', { precision: 28, scale: 10 }),
  exchangeRateSource: text('exchange_rate_source', { enum: ['base', 'table', 'manual'] }),
  tableRate: numeric('table_rate', { precision: 28, scale: 10 }),
  taxTreatment: text('tax_treatment', { enum: ['exclusive', 'inclusive', 'no_tax'] }).notNull(),
  discountType: text('discount_type', { enum: ['percent', 'amount'] }),
  discountValue: money('discount_value'),
  memo: text('memo').notNull().default(''),
  dimensionValueIds: uuid('dimension_value_ids').array().notNull().default([]),
  subtotal: money('subtotal').notNull().default('0'),
  discountTotal: money('discount_total').notNull().default('0'),
  taxTotal: money('tax_total').notNull().default('0'),
  recoverableTaxTotal: money('recoverable_tax_total').notNull().default('0'),
  total: money('total').notNull().default('0'),
  baseTotal: money('base_total'),
  amountDue: money('amount_due'),
  baseDue: money('base_due'),
  duplicateConfirmedReason: text('duplicate_confirmed_reason'),
  approvalRequestId: uuid('approval_request_id'),
  submittedByUserId: uuid('submitted_by_user_id'),
  submittedAt: timestamptz('submitted_at'),
  postedByUserId: uuid('posted_by_user_id'),
  postedAt: timestamptz('posted_at'),
  journalId: uuid('journal_id'),
  accountingEventId: uuid('accounting_event_id'),
  voidedByUserId: uuid('voided_by_user_id'),
  voidedAt: timestamptz('voided_at'),
  voidReason: text('void_reason'),
  voidJournalId: uuid('void_journal_id'),
  version: integer('version').notNull().default(1),
  createdByUserId: uuid('created_by_user_id').notNull(),
  createdAt: timestamptz('created_at').notNull(),
  updatedByUserId: uuid('updated_by_user_id'),
  updatedAt: timestamptz('updated_at').notNull(),
});

export const purchasesBillLines = pgTable('purchases_bill_lines', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull(),
  billId: uuid('bill_id').notNull(),
  lineNo: integer('line_no').notNull(),
  itemId: uuid('item_id'),
  description: text('description').notNull(),
  accountId: uuid('account_id'),
  quantity: numeric('quantity', { precision: 28, scale: 6 }).notNull(),
  unitPrice: numeric('unit_price', { precision: 28, scale: 6 }).notNull(),
  discountType: text('discount_type', { enum: ['percent', 'amount'] }),
  discountValue: money('discount_value'),
  amount: money('amount').notNull(),
  lineDiscount: money('line_discount').notNull().default('0'),
  documentDiscount: money('document_discount').notNull().default('0'),
  netAmount: money('net_amount').notNull(),
  taxCodeId: uuid('tax_code_id'),
  taxRateId: uuid('tax_rate_id'),
  taxRate: numeric('tax_rate', { precision: 7, scale: 4 }),
  taxAmount: money('tax_amount').notNull().default('0'),
  /** P4-12: the user's explicit choice (null: the default applies) and the resolved flag. */
  taxRecoverableOverride: boolean('tax_recoverable_override'),
  taxRecoverable: boolean('tax_recoverable').notNull().default(false),
  recoverableTax: money('recoverable_tax').notNull().default('0'),
  nonRecoverableTax: money('non_recoverable_tax').notNull().default('0'),
  /** P4-11: snapshotted at post. */
  inputTaxAccountId: uuid('input_tax_account_id'),
  total: money('total').notNull(),
  dimensionValueIds: uuid('dimension_value_ids').array().notNull().default([]),
});

// ---------------------------------------------------------------------------
// Vendor credits and debit notes (migration 0035; ADR 0004 P4-23, P4-24)
// ---------------------------------------------------------------------------

export const vendorCreditOrigins = ['supplier_credit_note', 'debit_note'] as const;
export type VendorCreditOrigin = (typeof vendorCreditOrigins)[number];
export const vendorCreditStatuses = ['DRAFT', 'PENDING_APPROVAL', 'POSTED', 'VOID'] as const;
export type VendorCreditStatus = (typeof vendorCreditStatuses)[number];

export const purchasesVendorCredits = pgTable('purchases_vendor_credits', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull(),
  origin: text('origin', { enum: vendorCreditOrigins }).notNull(),
  status: text('status', { enum: vendorCreditStatuses }).notNull().default('DRAFT'),
  vendorId: uuid('vendor_id').notNull(),
  /** An optional reference to a posted bill; not applied here (decided 2026-10-03). */
  billId: uuid('bill_id'),
  number: text('number'),
  /** The supplier's credit-note number (supplier credit notes), kept as entered. */
  vendorReference: text('vendor_reference'),
  vendorReferenceKey: text('vendor_reference_key').generatedAlwaysAs(
    // Documentation only: the column is generated by the database (migration 0035).
    sql`upper(regexp_replace(vendor_reference, '\\s', '', 'g'))`,
  ),
  creditDate: date('credit_date', { mode: 'string' }).notNull(),
  currencyCode: char('currency_code', { length: 3 }).notNull(),
  rateOverride: numeric('rate_override', { precision: 28, scale: 10 }),
  rateOverrideReason: text('rate_override_reason'),
  exchangeRate: numeric('exchange_rate', { precision: 28, scale: 10 }),
  exchangeRateSource: text('exchange_rate_source', { enum: ['base', 'table', 'manual', 'bill'] }),
  tableRate: numeric('table_rate', { precision: 28, scale: 10 }),
  taxTreatment: text('tax_treatment', { enum: ['exclusive', 'inclusive', 'no_tax'] }).notNull(),
  discountType: text('discount_type', { enum: ['percent', 'amount'] }),
  discountValue: money('discount_value'),
  memo: text('memo').notNull().default(''),
  dimensionValueIds: uuid('dimension_value_ids').array().notNull().default([]),
  subtotal: money('subtotal').notNull().default('0'),
  discountTotal: money('discount_total').notNull().default('0'),
  taxTotal: money('tax_total').notNull().default('0'),
  recoverableTaxTotal: money('recoverable_tax_total').notNull().default('0'),
  total: money('total').notNull().default('0'),
  baseTotal: money('base_total'),
  amountUnapplied: money('amount_unapplied'),
  baseUnapplied: money('base_unapplied'),
  approvalRequestId: uuid('approval_request_id'),
  submittedByUserId: uuid('submitted_by_user_id'),
  submittedAt: timestamptz('submitted_at'),
  postedByUserId: uuid('posted_by_user_id'),
  postedAt: timestamptz('posted_at'),
  journalId: uuid('journal_id'),
  accountingEventId: uuid('accounting_event_id'),
  renderSnapshot: jsonb('render_snapshot').$type<Record<string, unknown>>(),
  pdfFileId: uuid('pdf_file_id'),
  voidedByUserId: uuid('voided_by_user_id'),
  voidedAt: timestamptz('voided_at'),
  voidReason: text('void_reason'),
  voidJournalId: uuid('void_journal_id'),
  version: integer('version').notNull().default(1),
  createdByUserId: uuid('created_by_user_id').notNull(),
  createdAt: timestamptz('created_at').notNull(),
  updatedByUserId: uuid('updated_by_user_id'),
  updatedAt: timestamptz('updated_at').notNull(),
});

export const purchasesVendorCreditLines = pgTable('purchases_vendor_credit_lines', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull(),
  vendorCreditId: uuid('vendor_credit_id').notNull(),
  lineNo: integer('line_no').notNull(),
  itemId: uuid('item_id'),
  description: text('description').notNull(),
  accountId: uuid('account_id'),
  quantity: numeric('quantity', { precision: 28, scale: 6 }).notNull(),
  unitPrice: numeric('unit_price', { precision: 28, scale: 6 }).notNull(),
  discountType: text('discount_type', { enum: ['percent', 'amount'] }),
  discountValue: money('discount_value'),
  amount: money('amount').notNull(),
  lineDiscount: money('line_discount').notNull().default('0'),
  documentDiscount: money('document_discount').notNull().default('0'),
  netAmount: money('net_amount').notNull(),
  taxCodeId: uuid('tax_code_id'),
  taxRateId: uuid('tax_rate_id'),
  taxRate: numeric('tax_rate', { precision: 7, scale: 4 }),
  taxAmount: money('tax_amount').notNull().default('0'),
  taxRecoverableOverride: boolean('tax_recoverable_override'),
  taxRecoverable: boolean('tax_recoverable').notNull().default(false),
  recoverableTax: money('recoverable_tax').notNull().default('0'),
  nonRecoverableTax: money('non_recoverable_tax').notNull().default('0'),
  inputTaxAccountId: uuid('input_tax_account_id'),
  total: money('total').notNull(),
  dimensionValueIds: uuid('dimension_value_ids').array().notNull().default([]),
});

export const purchasesDocumentEmails = pgTable('purchases_document_emails', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull(),
  documentType: text('document_type', { enum: ['debit_note'] }).notNull(),
  documentId: uuid('document_id').notNull(),
  recipient: text('recipient').notNull(),
  subject: text('subject').notNull(),
  message: text('message').notNull().default(''),
  status: text('status', { enum: ['queued', 'sent', 'failed'] })
    .notNull()
    .default('queued'),
  jobId: uuid('job_id'),
  fileId: uuid('file_id'),
  requestedByUserId: uuid('requested_by_user_id').notNull(),
  requestedAt: timestamptz('requested_at').notNull(),
  sentAt: timestamptz('sent_at'),
});
