import { randomUUID } from 'node:crypto';
import { createReadStream, createWriteStream } from 'node:fs';
import { mkdir, readdir, rename, rm, stat } from 'node:fs/promises';
import path from 'node:path';
import type { Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';

/**
 * Storage provider abstraction (Decision 6; S5-02). File contents never go into PostgreSQL.
 * Keys are generated by the server (S5-03) and validated here as well, so a provider can never
 * be asked to touch a path outside its root.
 */
export interface StorageObject {
  key: string;
  modifiedAt: Date;
}

export interface StorageProvider {
  readonly name: 'local';
  put(key: string, content: Readable): Promise<void>;
  get(key: string): Promise<Readable>;
  delete(key: string): Promise<void>;
  exists(key: string): Promise<boolean>;
  /** Objects under a tenant prefix (`org/{organizationId}/`), for the orphan sweep. */
  list(prefix: string): Promise<StorageObject[]>;
}

const UUID = '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}';
export const STORAGE_KEY = new RegExp(`^org/${UUID}/\\d{4}/\\d{2}/${UUID}$`);
const TENANT_PREFIX = new RegExp(`^org/${UUID}/$`);

/** `org/{organizationId}/{yyyy}/{mm}/{fileId}`: tenant-prefixed and never user-controlled. */
export function storageKeyFor(organizationId: string, fileId: string, at: Date): string {
  const yyyy = String(at.getUTCFullYear());
  const mm = String(at.getUTCMonth() + 1).padStart(2, '0');
  const key = `org/${organizationId}/${yyyy}/${mm}/${fileId}`;
  if (!STORAGE_KEY.test(key)) throw new Error('Invalid storage key');
  return key;
}

export function tenantPrefix(organizationId: string): string {
  const prefix = `org/${organizationId}/`;
  if (!TENANT_PREFIX.test(prefix)) throw new Error('Invalid tenant prefix');
  return prefix;
}

/** Development provider: files under a local root (default: the git-ignored .data/storage). */
export class LocalStorageProvider implements StorageProvider {
  readonly name = 'local' as const;
  private readonly root: string;

  constructor(root: string) {
    this.root = path.resolve(root);
  }

  /** Resolves a validated key and refuses anything that escapes the root. */
  private pathFor(key: string, pattern: RegExp = STORAGE_KEY): string {
    if (!pattern.test(key)) throw new Error('Invalid storage key');
    const resolved = path.resolve(this.root, ...key.split('/'));
    if (!resolved.startsWith(this.root + path.sep)) throw new Error('Storage key outside root');
    return resolved;
  }

  async put(key: string, content: Readable): Promise<void> {
    const target = this.pathFor(key);
    await mkdir(path.dirname(target), { recursive: true });
    // Write to a sibling temporary file and rename, so a partial object is never visible.
    const temporary = `${target}.${randomUUID()}.partial`;
    try {
      await pipeline(content, createWriteStream(temporary, { flags: 'wx' }));
      await rename(temporary, target);
    } catch (error) {
      await rm(temporary, { force: true });
      throw error;
    }
  }

  async get(key: string): Promise<Readable> {
    const target = this.pathFor(key);
    await stat(target);
    return createReadStream(target);
  }

  async delete(key: string): Promise<void> {
    await rm(this.pathFor(key), { force: true });
  }

  async exists(key: string): Promise<boolean> {
    try {
      await stat(this.pathFor(key));
      return true;
    } catch {
      return false;
    }
  }

  async list(prefix: string): Promise<StorageObject[]> {
    const base = this.pathFor(prefix, TENANT_PREFIX);
    const out: StorageObject[] = [];
    const walk = async (dir: string, parts: string[]): Promise<void> => {
      let entries;
      try {
        entries = await readdir(dir, { withFileTypes: true });
      } catch {
        return;
      }
      for (const entry of entries) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
          await walk(full, [...parts, entry.name]);
        } else if (entry.isFile()) {
          const key = `${prefix}${[...parts, entry.name].join('/')}`;
          if (STORAGE_KEY.test(key)) out.push({ key, modifiedAt: (await stat(full)).mtime });
        }
      }
    };
    await walk(base, []);
    return out;
  }
}
