import type { Decimal } from 'decimal.js';
import { decimal, isSupportedCurrency, parseAmount } from '../../domain/money.js';
import type { JournalLineKind } from './schema.js';
import type { AccountFacts, RuleIssue } from './rules.js';

/**
 * System journals (Decision 10, ADR 0002 A1.1): journals generated by approved accounting
 * handlers rather than typed by a user. They may carry explicit per-line base amounts and, for
 * the FX/revaluation handlers only, base-currency-only lines. Pure rules; no database access.
 */

/**
 * Approved system-journal source types. `baseOnly` marks the FX/revaluation handlers that may
 * post base-only lines; the database guard carries the same allowlist.
 */
export const SYSTEM_JOURNAL_TYPES = {
  realized_fx: { baseOnly: true },
  revaluation: { baseOnly: true },
  revaluation_reversal: { baseOnly: true },
  opening_balance: { baseOnly: false },
} as const satisfies Record<string, { baseOnly: boolean }>;
export type SystemJournalType = keyof typeof SYSTEM_JOURNAL_TYPES;

export function isSystemJournalType(value: string): value is SystemJournalType {
  return Object.hasOwn(SYSTEM_JOURNAL_TYPES, value);
}

/**
 * System FX/revaluation journals (realized FX, revaluation, revaluation reversal). Decision 80:
 * they are corrected through their FX/revaluation process, never by generic manual reversal,
 * whether or not they contain base-only lines.
 */
export function isFxSystemJournal(journal: { source: string; sourceType: string | null }): boolean {
  return (
    journal.source === 'system' &&
    journal.sourceType !== null &&
    isSystemJournalType(journal.sourceType) &&
    SYSTEM_JOURNAL_TYPES[journal.sourceType].baseOnly
  );
}

export interface SourceRef {
  module: string;
  type: string;
  id: string;
}

export interface SystemJournalLineInput {
  accountId: string;
  description: string;
  kind: JournalLineKind;
  /** Transaction-currency amounts (normal lines only). */
  debit: string | null;
  credit: string | null;
  /** Explicit base amounts: required on base-only lines; all-or-none on normal lines. */
  baseDebit: string | null;
  baseCredit: string | null;
  /** Dimensions set by the originating module's own rules (Decision 78). */
  dimensions?: readonly { dimensionTypeId: string; dimensionValueId: string }[];
}

export interface PreparedSystemLine {
  lineNumber: number;
  kind: JournalLineKind;
  accountId: string;
  side: 'debit' | 'credit';
  /** Transaction amount (normal lines). */
  amount: Decimal | null;
  /** Explicit base amount, when supplied. */
  baseAmount: Decimal | null;
}

const SOURCE_MODULE = /^[a-z][a-z0-9_-]*$/;

/**
 * Validates a system journal: an approved source type, >= 2 lines, active leaf accounts, line
 * shapes per kind, base-only lines only for FX/revaluation types, the account-currency rule
 * with the Decision 71 exception, and transaction balance across normal lines. The base balance
 * is checked by the posting engine once every line has its base amount.
 */
export function validateSystemJournal(
  input: {
    sourceType: string;
    sourceModule: string;
    currency: string;
    baseCurrency: string;
    lines: readonly SystemJournalLineInput[];
  },
  accounts: ReadonlyMap<string, AccountFacts>,
):
  | { ok: true; lines: PreparedSystemLine[]; total: Decimal; explicitBase: boolean }
  | { ok: false; issues: RuleIssue[] } {
  const issues: RuleIssue[] = [];
  if (!isSystemJournalType(input.sourceType)) {
    return {
      ok: false,
      issues: [{ path: 'sourceType', message: `Unknown system journal type ${input.sourceType}.` }],
    };
  }
  if (!SOURCE_MODULE.test(input.sourceModule)) {
    issues.push({ path: 'sourceModule', message: 'Invalid source module.' });
  }
  if (!isSupportedCurrency(input.currency)) {
    issues.push({ path: 'currency', message: `Unsupported currency ${input.currency}.` });
    return { ok: false, issues };
  }
  const baseOnlyAllowed = SYSTEM_JOURNAL_TYPES[input.sourceType].baseOnly;
  if (input.lines.length < 2) {
    issues.push({ path: 'lines', message: 'A journal needs at least two lines.' });
  }

  const normalWithBase = input.lines.filter(
    (l) => l.kind === 'normal' && (l.baseDebit !== null || l.baseCredit !== null),
  ).length;
  const normalCount = input.lines.filter((l) => l.kind === 'normal').length;
  if (normalWithBase !== 0 && normalWithBase !== normalCount) {
    issues.push({
      path: 'lines',
      message: 'Explicit base amounts must be given on every normal line or on none.',
    });
  }

  const prepared: PreparedSystemLine[] = [];
  input.lines.forEach((line, i) => {
    const path = `lines.${i}`;
    const account = accounts.get(line.accountId);
    if (!account) {
      issues.push({ path: `${path}.accountId`, message: 'Unknown account.' });
    } else if (account.status !== 'ACTIVE') {
      issues.push({
        path: `${path}.accountId`,
        message: 'Archived accounts cannot receive postings.',
      });
    } else if (!account.isLeaf) {
      issues.push({
        path: `${path}.accountId`,
        message: 'Only leaf accounts can receive postings.',
      });
    } else if (account.currencyCode !== undefined) {
      const allowed =
        line.kind === 'normal'
          ? account.currencyCode === input.currency || account.currencyCode === input.baseCurrency
          : account.currencyCode === input.baseCurrency || account.isMonetary === true;
      if (!allowed) {
        issues.push({
          path: `${path}.accountId`,
          message:
            line.kind === 'normal'
              ? `This account is in ${account.currencyCode}; lines may post only to accounts in the journal or base currency.`
              : 'Base-only lines post only to base-currency accounts or foreign-currency monetary accounts.',
        });
      }
    }

    const base = parseSide(line.baseDebit, line.baseCredit, input.baseCurrency);
    if (line.kind === 'base_only') {
      if (!baseOnlyAllowed) {
        issues.push({
          path: `${path}.kind`,
          message: 'Base-only lines are restricted to FX and revaluation journals.',
        });
      }
      if (line.debit !== null || line.credit !== null) {
        issues.push({ path, message: 'Base-only lines have no transaction amount.' });
      }
      if (!base.ok || !base.value) {
        issues.push({
          path,
          message: `Base-only lines need exactly one base amount.${base.ok ? '' : ` ${base.message}`}`,
        });
      } else {
        prepared.push({
          lineNumber: i + 1,
          kind: 'base_only',
          accountId: line.accountId,
          side: base.value.side,
          amount: null,
          baseAmount: base.value.amount,
        });
      }
      return;
    }

    const txn = parseSide(line.debit, line.credit, input.currency);
    if (!txn.ok || !txn.value) {
      issues.push({
        path,
        message: `Every normal line needs exactly one transaction amount.${txn.ok ? '' : ` ${txn.message}`}`,
      });
      return;
    }
    if (!base.ok) {
      issues.push({ path, message: base.message });
      return;
    }
    if (base.value && base.value.side !== txn.value.side) {
      issues.push({
        path,
        message: 'A normal line has its base amount on the same side as its transaction amount.',
      });
      return;
    }
    prepared.push({
      lineNumber: i + 1,
      kind: 'normal',
      accountId: line.accountId,
      side: txn.value.side,
      amount: txn.value.amount,
      baseAmount: base.value?.amount ?? null,
    });
  });
  if (issues.length > 0) return { ok: false, issues };

  const sum = (side: 'debit' | 'credit') =>
    prepared
      .filter((l) => l.kind === 'normal' && l.side === side)
      .reduce((acc, l) => acc.plus(l.amount!), decimal(0));
  const debit = sum('debit');
  const credit = sum('credit');
  if (!debit.eq(credit)) {
    return {
      ok: false,
      issues: [
        {
          path: 'lines',
          message: `Transaction debits (${debit.toFixed()}) must equal transaction credits (${credit.toFixed()}) across normal lines.`,
        },
      ],
    };
  }
  return { ok: true, lines: prepared, total: debit, explicitBase: normalWithBase > 0 };
}

function parseSide(
  debit: string | null,
  credit: string | null,
  currency: string,
):
  | { ok: true; value: { side: 'debit' | 'credit'; amount: Decimal } | null }
  | { ok: false; message: string } {
  if (debit !== null && credit !== null) {
    return { ok: false, message: 'A line has either a debit or a credit, never both.' };
  }
  const raw = debit ?? credit;
  if (raw === null) return { ok: true, value: null };
  const parsed = parseAmount(raw, currency);
  if (!parsed.ok) {
    return { ok: false, message: `Invalid ${currency} amount ${raw}.` };
  }
  return { ok: true, value: { side: debit !== null ? 'debit' : 'credit', amount: parsed.value } };
}
